name: ershad
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^20.1.52-beta

cupertino_icons: ^1.0.2

dev_dependencies:

flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Ershad"

flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - pic/pic1.png
    - pic/pic2.jpg